const SubmitTimesheetActionTypes = {
  TOGGLE_PICKER_HIDDEN: 'TOGGLE_PICKER_HIDDEN',
  SET_SELECTED_DAYS: 'SET_SLECTED_DAYS',
  SET_HOVER_RANGE: 'SET_HOVER_RANGE',
  SET_TIMESHEET_DATA: 'SET_TIMESHEET_DATA',
  SET_WEEK_NUMBER: 'SET_WEEK_NUMBER'
};

export default SubmitTimesheetActionTypes;
