const SubmitTimesheetActionTypes = {
  ST_TOGGLE_PICKER_HIDDEN: 'ST_TOGGLE_PICKER_HIDDEN',
  ST_SET_SELECTED_DAYS: 'ST_SET_SLECTED_DAYS',
  ST_SET_HOVER_RANGE: 'STSET_HOVER_RANGE',
  ST_SET_TIMESHEET_DATA: 'ST_SET_TIMESHEET_DATA',
  ST_SET_WEEK_NUMBER: 'ST_SET_WEEK_NUMBER'
};

export default SubmitTimesheetActionTypes;
