const ViewTimesheetActionTypes = {
  TOGGLE_PICKER_HIDDEN: 'TOGGLE_PICKER_HIDDEN',
  SET_SELECTED_DAYS: 'SET_SLECTED_DAYS',
  SET_HOVER_RANGE: 'SET_HOVER_RANGE',
  SET_WEEK_NUMBER: 'SET_WEEK_NUMBER',
  SET_VIEWTS_DATA:'SET_VIEWTS_DATA'
};

export default ViewTimesheetActionTypes;
